### ISSUE TITLE
ERROR ESP requests password, but no password given!

### ISSUE THREAD

**Issue by jazzmonger** [KaufHA/PLF10#14]
I have 3 of your plugs. 2 flash fine.  I'm trying to send a simple config file to the 3rd one:

```
substitutions:
  name: solar-shed-batt-heaters
  friendly_name: Solar Shed Batt Heaters

packages:
  Kauf.PLF10: github://KaufHA/PLF10/kauf-plug.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Solar-Shed-Batt-Heaters"
    password: !secret wifi_password
```

======================= [SUCCESS] Took 97.42 seconds =========================
INFO Successfully compiled program.
INFO Resolving IP address of solar-shed-batt-heaters.local
INFO  -> 192.168.1.223
INFO Uploading /data/solar-shed-batt-heaters/.pioenvs/solar-shed-batt-heaters/firmware.bin (551232 bytes)
INFO Compressed to 375036 bytes
**ERROR ESP requests password, but no password given!**

l've tried resetting the esp but the issue remains.

Otherwise I'm super impressed!  The full yaml file is a really good study of what can be done in ESPHome.  I thought my 500 line config file that controls my wood pellet stove was impressive.. this has me beat by a mile!
