### ISSUE TITLE
Is there a way to guarantee that relay stays closed?

### ISSUE THREAD

**Issue by sowbug** [KaufHA/PLF10#24]
I'm using a Kauf Plug as a power meter for my desk, which includes my computer. Twice in the past few months my power has suddenly glitched, computer restarts, chaos ensues, etc. Today I figured out that the Kauf plug was responsible. I think it lost its connection to the internet, and like any ESPHome device rebooted in the hopes of restoring the connection.

That's normally a great feature, but in this case it makes the plug a lot less useful for my intended purpose.

I see `reboot_timeout` in https://esphome.io/components/wifi, and I'm about to try it like so:

```
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
```

Does this sound right? Is there anything else I can do to configure the plug to never, ever, ever turn off the outlet?
